set(FILE_STREAM_BLOCK_SIZE "2097152" CACHE STRING "Block size")
set(SPEED_TEST_FILE_SIZE_MB "8096" CACHE STRING "File size in MiB")

add_definitions(-DFILE_STREAM_BLOCK_SIZE=${FILE_STREAM_BLOCK_SIZE})
add_definitions(-DSPEED_TEST_FILE_SIZE_MB=${SPEED_TEST_FILE_SIZE_MB})

set(CMAKE_CXX_FLAGS  "-march=native ${CMAKE_CXX_FLAGS}")
set(CMAKE_C_FLAGS    "-march=native ${CMAKE_C_FLAGS}")
